### ISSUE TITLE
Ingress

### ISSUE THREAD

**Issue by ushdjkfnf** [ushdjkfnf/ushdjkfnf.github.io#108]
- log format custom

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
data:
  log-format-upstream: '$http_x_forwarded_for - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id;'
```
