### ISSUE TITLE
Ceph

### ISSUE THREAD

**Issue by ushdjkfnf** [ushdjkfnf/ushdjkfnf.github.io#123]
- ceph deploy
plays/ceph

- ceph block pool
```
ceph osd pool create kube_cephblock 100 100
rbd pool init kube_cephblock
ceph osd pool set kube_cephblock size 3
ceph osd pool application enable kube_cephblock rbd

```

- ceph filesystem pool
```
ceph osd pool create kube_cephfs_data 32
ceph osd pool create kube_cephfs_meta 32
ceph fs new kube kube_cephfs_meta kube_cephfs_data
ceph osd pool set cephfs_data size 3
ceph osd pool set cephfs_meta size 3
```

- ceph auth
```
ceph auth caps client.kube mon 'allow all' osd 'allow all' mgr 'allow all'
```

- ceph-csi-config.yaml
```yaml
---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "6edd9bf5-d996-4ff8-9ef8-d744c981e4f6",
        "monitors": [
          "172.17.1.121:6789",
          "172.17.1.153:6789",
          "172.17.1.198:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
```

- ceph-csi-secret.yaml
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
stringData:
  userID: kube
  userKey: AQC9PlJeAzhrMBAAXn2n0+BsGd5B7P8yy0o3hA==
```

- kms-config.yaml
```yaml
---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    {
    }
metadata:
  name: ceph-csi-encryption-kms-config

```
> https://raw.githubusercontent.com/ceph/ceph-csi/master/examples/kms/vault/kms-config.yaml

- ceph rbac

```
kubectl apply -f https://raw.githubusercontent.com/ceph/ceph-csi/master/deploy/rbd/kubernetes/csi-provisioner-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/ceph/ceph-csi/master/deploy/rbd/kubernetes/csi-nodeplugin-rbac.yaml

```
- ceph operator

```
wget https://raw.githubusercontent.com/ceph/ceph-csi/master/deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
kubectl apply -f csi-rbdplugin-provisioner.yaml
wget https://raw.githubusercontent.com/ceph/ceph-csi/master/deploy/rbd/kubernetes/csi-rbdplugin.yaml
kubectl apply -f csi-rbdplugin.yaml
```

- ceph-block-sc.yaml
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-block-sc
provisioner: rbd.csi.ceph.com
parameters:
   clusterID: 6edd9bf5-d996-4ff8-9ef8-d744c981e4f6
   pool: kube_cephblock
   csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
   csi.storage.k8s.io/provisioner-secret-namespace: default
   csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
   csi.storage.k8s.io/node-stage-secret-namespace: default
reclaimPolicy: Delete
mountOptions:
   - discard
```

- ceph-block-demo-pod-pvc.yaml
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-block-demo-pod-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block-sc

```
- ceph-block-demo-pod.yaml
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: ceph-block-demo-pod
spec:
  containers:
    - name: fc-container
      image: fedora:26
      command: ["/bin/sh", "-c"]
      args: ["tail -f /dev/null"]
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: ceph-block-demo-pod-pvc

```

- ceph-fs-sc.yaml
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-fs-sc
provisioner: rbd.csi.ceph.com
parameters:
   clusterID: 6edd9bf5-d996-4ff8-9ef8-d744c981e4f6
   pool: kube_cephfs_data
   csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
   csi.storage.k8s.io/provisioner-secret-namespace: default
   csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
   csi.storage.k8s.io/node-stage-secret-namespace: default
reclaimPolicy: Retain
mountOptions:
   - discard
```

- ceph-fs-pvc.yaml
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-fs-demo-pod-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-fs-sc

```

- ceph-fs-demo-pod.yaml
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: ceph-fs-demo-pod
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: ceph-fs-demo-pod-pvc
        readOnly: false

```
