### ISSUE TITLE
Installing gitea on k8s

### ISSUE THREAD

**Issue by ushdjkfnf** [ushdjkfnf/ushdjkfnf.github.io#94]
- git-pvc.yaml
```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitpv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    # server: nfs-server.default.svc.cluster.local
    server: 13.251.134.149
    path: "/nfs/git"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitclaim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem

  resources:
    requests:
      storage: 20Gi
  storageClassName: slow

```

- gitea.yaml
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: gitea
  name: gitea
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: gitea

  template:
    metadata:
      labels:
        run: gitea
    spec:
      containers:
      # - image: ops2020/gogs:latest
      - image: gitea/gitea:latest
        imagePullPolicy: IfNotPresent
        name: gitea
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
            - mountPath: /data
              name: mypd

      volumes:
          - name: mypd
            persistentVolumeClaim:
                claimName: gitclaim

---
apiVersion: v1
kind: Service
metadata:
    name: gitea

spec:
    selector:
        run: gitea
    ports:
        - name: default
          protocol: TCP
          port: 80
          targetPort: 3000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: gitea-ingress

spec:
    rules:
        - host: git.wtalking.chat
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: gitea
                        servicePort: 80

```
