### ISSUE TITLE
Installing Habor on k8s

### ISSUE THREAD

**Issue by ushdjkfnf** [ushdjkfnf/ushdjkfnf.github.io#95]
- harbor-pvc.yaml
```yaml

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: harbor
  nfs:
    # server: nfs-server.default.svc.cluster.local
    server: 13.251.134.149
    path: "/nfs/harbor"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem

  resources:
    requests:
      storage: 30Gi
  storageClassName: harbor

```

- harbor-config.yaml

```yaml

externalURL: http://registry.wtalking.chat

expose:
  type: ingress
  tls:
    enabled: false

  ingress:
    hosts:
      core: registry.wtalking.chat
      notary: registry.wtalking.chat

persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: "harbor"
      storageClass: "harbor"
      subPath: "./registry"
      accessMode: ReadWriteOnce
      size: 15Gi

    chartmuseum:
      existingClaim: "harbor"
      storageClass: "harbor"
      subPath: "./chartmuseum"
      accessMode: ReadWriteOnce
      size: 5Gi

    jobservice:
      existingClaim: "harbor"
      storageClass: "harbor"
      subPath: "./jobservice"
      accessMode: ReadWriteOnce
      size: 2Gi

    database:
      existingClaim: "harbor"
      storageClass: "harbor"
      subPath: "./database"
      accessMode: ReadWriteOnce
      size: 4Gi

    redis:
      existingClaim: "harbor"
      storageClass: "harbor"
      subPath: "./redis"
      accessMode: ReadWriteOnce
      size: 4Gi

  # imageChartStorage:
  #   disableredirect: true

```
